#! /bin/bash

mkdir -p /mnt/sync/folders
mkdir -p /mnt/sync/config

if [ -f /mnt/sync/sync.conf ]; then
    rm -f /tmp/sync.conf;
else
    mv /tmp/sync.conf /mnt/sync/sync.conf;
fi

exec /usr/bin/rslsync --nodaemon $*
