#! /bin/bash

mkdir -p /mnt/sync/folders
mkdir -p /mnt/sync/config

if [ -f /mnt/sync/sync.conf ]; then
    mv /etc/sync.conf /etc/sync.conf.default;
else
    mv /etc/sync.conf /mnt/sync/sync.conf;
fi

exec /usr/bin/rslsync --nodaemon $*
