#!/bin/bash

# Custom build script to build images for all supported architectures.
#
# Example for IMAGE_NAME: resilio/sync:release-2.6.3
# Images built:
# - resilio/sync:release-2.6.3-amd64
# - resilio/sync:release-2.6.3-arm32v7

for arch in amd64 arm32v7
do
  echo "Building $IMAGE_NAME-$arch"
  docker build --build-arg FROM_ARCH=$arch --file $DOCKERFILE_PATH --tag $IMAGE_NAME-$arch .
done
